displayName: RemoteAddr (fix X-Forwarded-Port)
type: middleware
iconPath: .assets/icon.png

import: github.com/RiskIdent/traefik-remoteaddr-plugin

summary: "Add request header for the client port, to make X-Forwarded-Port act like in nginx"

testData:
  headers:
    port: X-Forwarded-Port
